// KINI ANG IMONG OFFLINE DATABASE
const riderDatabase = [
  { idNum: "0000", fullname: "ELKAPITAN", nickname: "invictus", level: "Street Pilot", category: "Adventure 500cc", classification: "Street Pilot", passcode: "a045f58fe4162bb9227e93f549390aef6219914df85029f74f6057c3fda6ca85", isMarshal: true },
  { idNum: "0001", fullname: "technicus", nickname: "rayHARGG", level: "AS26", category: "Adventure 525cc", classification: "Aspirant", passcode: "4c327801d652b4e7b3449684f83febb4fea62dbd2c80ee4136f32ecbccc0f45e", isMarshal: true },
  { idNum: "0002", fullname: "Long Way Ph", nickname: "Elkapitan Jr", level: "AS26", category: "ADV 350cc", classification: "MASTER", passcode: "e40e0225f947f1ae6cba2245dd9a1a50361512bb718c1ca1ce3f983fe3b3aa4e", isMarshal: true },
  { idNum: "0017", fullname: "MCcoy", nickname: "17", level: "G5", category: "BMW GS450cc", classification: "MASTER", passcode: "fe2592b42a727e977f055947385b709cc82b16b9a87f88c6abf3900d65d0cdc3", isMarshal: false },
  { idNum: "0251", fullname: "Zhack", nickname: "zhackyyy", level: "G1S", category: "Rouser RS2000", classification: "Aspirant", passcode: "e0799b5b526a8866b02243691e20c51cf33ef66d84c7c4e3b99727aa48d21d20", isMarshal: false  },
  { idNum: "1001", fullname: "Juan Dela Cruz", nickname: "Juan", level: "G5", category: "Adventure 1000cc", classification: "Veteran" }, 
  { idNum: "1002", fullname: "Pedro Penduko", nickname: "Pedz", level: "SKM26", category: "Scooter 155cc", classification: "Novice" },
  { idNum: "1234", fullname: "Prof G", nickname: "Master", level: "SKM26", category: "Enduro", classification: "Novice" },
  { idNum: "2026", fullname: "Master Prof", nickname: "Prof G", level: "G0D", category: "Enduro 250cc", classification: "Master" },
  { idNum: "1583", fullname: "RABAGO, RUNMEN JAN", nickname: "Accountant MOTO", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1584", fullname: "Abides, John Lloyd Francis ", nickname: "BEST J", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1585", fullname: "Marilao, Clovis", nickname: "cloVis", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1586", fullname: "Montoya, John Ronald", nickname: "THROTTLE THERAPY PH 128", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1587", fullname: "Magdayao, Zandro jay", nickname: "CJM", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1588", fullname: "Oculam, Crizel", nickname: "CRIZ TAKAHASHI 23", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1589", fullname: "Repuelo, Jezreel ", nickname: "JAMPUE", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1590", fullname: "Abrogueña, Oin", nickname: "ACID BURN", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1591", fullname: "LLIDO, WARREN", nickname: "WA WAY", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1592", fullname: "Miguel, Raymon ching", nickname: "Monchingmoto", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1593", fullname: "VIRAY, ARTHUR KENNETH ", nickname: "artken", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1594", fullname: "Betos, Elmer", nickname: "Merat d great", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1595", fullname: "Kapili, Raldi", nickname: "R Kap", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1596", fullname: "Dy, Jan Russel", nickname: "RDY", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1597", fullname: "Villaluna, Jeffrey", nickname: "Jepoy", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1598", fullname: "Retorta, Edwin", nickname: "Ride with Ed", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1599", fullname: "GAMUETA, JEFFREY", nickname: "Charles Kingston", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1600", fullname: "Pamisa, Warren", nickname: "wewao26", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1601", fullname: "Senorio, Jake Lester", nickname: "BOSS JAKE", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1602", fullname: "Nahial, Romer", nickname: "RDN", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1603", fullname: "PAGOCAG, EDRIS", nickname: "EdPags", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1604", fullname: "CAMANZO, JESRYL", nickname: "DONGSKIE CC", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1605", fullname: "Jabla, Joshua ", nickname: "JOSHUA", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1606", fullname: "Indino, Vernon", nickname: "VENOM", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1607", fullname: "Onofre, Jibreel", nickname: "Jiby", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1608", fullname: "Gonzaga, Robert ian", nickname: "Ghost 6*4*6*", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1609", fullname: "PADRONES, ROCKY", nickname: "RaKiE", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1610", fullname: "Canoy, Ronron", nickname: "yonac r.r", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1611", fullname: "UYANGUREN, KAHLIL", nickname: "Kah Inggo", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1612", fullname: "Delector, Efer John", nickname: "E-John", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1613", fullname: "Rendon, Wilven ", nickname: "WR", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1614", fullname: "CHUAQUICO, RYAN S.", nickname: "KHEE RAI", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1615", fullname: "Tesoro, Welbourn", nickname: "TESORO W.", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1616", fullname: "Tagupa, Charlston", nickname: "toniiks", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1617", fullname: "REMOLLENO, ALEXANDER ", nickname: "XRM SAKALAM", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1618", fullname: "Cadorniga, Murphy", nickname: "MC", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1619", fullname: "BAJENTING, JOSE", nickname: "JB", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1620", fullname: "Desalan, Jayson Labesores", nickname: "PAGE JUAN ", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1621", fullname: "Resurreccion, Ram", nickname: "RAM", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1622", fullname: "Mantalaba, Mc Sherwin", nickname: "MCshe", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1623", fullname: "Sultan, Nassive", nickname: "Nassive", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1624", fullname: "Sulapas, Jhomar", nickname: "Sulapas", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1625", fullname: "Diamla, Ibsar Jr", nickname: "Diamla", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1634", fullname: "Galvadores, Riche Val", nickname: "Long Way PH", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  { idNum: "1635", fullname: "German, Henry Gulle", nickname: "technicus", level: "AS26", category: "LONEWOLF", classification: "MASTER" },
  
  // Dinhi nimo isumpay ang ubang riders...
];