// ==========================================
// MASTERMINDS'CUP - CENTRAL DATABASE (v4.0)
// ==========================================

// 1. RIDER MASTERLIST (Mga ID, pangalan, ug Hashed Passcodes)
const riderDatabase = [
    { idNum: "0000", fullname: "ELKAPITAN", nickname: "invictus", level: "Street Pilot", category: "Adventure", classification: "Street Pilot", vehicle: "Bristol 500", passcode: "a045f58fe4162bb9227e93f549390aef6219914df85029f74f6057c3fda6ca85", isMarshal: true, expiry: "2026-12-31" },
    { idNum: "0001", fullname: "technicus", nickname: "rayHARGG", level: "AS26", category: "Touring", classification: "Aspirant", vehicle: "Rouser NS200", passcode: "4c327801d652b4e7b3449684f83febb4fea62dbd2c80ee4136f32ecbccc0f45e", isMarshal: true, expiry: "2028-12-31" },
    { idNum: "0002", fullname: "Long Way Ph", nickname: "Elkapitan Jr", level: "AS26", category: "Adeventure", classification: "MASTER", vehicle: "Yamaha ADV350", passcode: "e40e0225f947f1ae6cba2245dd9a1a50361512bb718c1ca1ce3f983fe3b3aa4e", isMarshal: true, expiry: "2027-12-31" },
    { idNum: "0017", fullname: "MCcoy", nickname: "17", level: "G5", category: "Adventure", classification: "MASTER", vehicle: "BMW GS450", passcode: "fe2592b42a727e977f055947385b709cc82b16b9a87f88c6abf3900d65d0cdc3", isMarshal: false, expiry: "2026-12-31" },
    { idNum: "0251", fullname: "Zhack", nickname: "zhackyyy", level: "G1S", category: "Racing", classification: "Aspirant", vehicle: "Rouser RS200", passcode: "e0799b5b526a8866b02243691e20c51cf33ef66d84c7c4e3b99727aa48d21d20", isMarshal: false, expiry: "2028-12-31" },
    { idNum: "1605", fullname: "Jabla, Joshua ", nickname: "JOSHUA", level: "AS26", category: "LONEWOLF", classification: "MASTER", vehicle: "", passcode: "5492dcdcf24546ce707e4c6e370ab4a0736d0defa0cbbf6f66798e57a309c6a1", isMarshal: false, expiry: "2026-09-30" },
    { idNum: "1609", fullname: "PADRONES, ROCKY", nickname: "RaKiE", level: "AS26", category: "LONEWOLF", classification: "MASTER", vehicle: "", passcode: "e40e0225f947f1ae6cba2245dd9a1a50361512bb718c1ca1ce3f983fe3b3aa4e", isMarshal: false, expiry: "2026-09-30" },
    { idNum: "1617", fullname: "REMOLLENO, ALEXANDER ", nickname: "XRM SAKALAM", level: "AS26", category: "LONEWOLF", classification: "MASTER", vehicle: "", passcode: "9f2ca3ad31656671b9e0bf12509c9e71dac5b8e8834145767f684bf193945d33", isMarshal: false, expiry: "2026-09-30" },
    { idNum: "1634", fullname: "Galvadores, Riche Val", nickname: "Long Way PH", level: "AS26", category: "LONEWOLF", classification: "MASTER", vehicle: "", passcode: "0", isMarshal: false, expiry: "2027-12-31" },
    { idNum: "1635", fullname: "German, Henry Gulle", nickname: "technicus", level: "AS26", category: "LONEWOLF", classification: "MASTER", vehicle: "", passcode: "0", isMarshal: false, expiry: "2028-12-31" },
    { idNum: "1636", fullname: "WAWAY", nickname: "wa way", level: "G3", category: "LONEWOLF", classification: "MASTER", vehicle: "Doming", passcode: "6161b2838ffa6ce17b84db3b45b4f8437855ecf43e75de2d1ad0008eaae91aa0", isMarshal: false, expiry: "2026-12-31" }
];


// --- ROUTE DESCRIPTIONS / FULL NAMES ---
const routeNames = {
    "G1N": "777 (North) MaKahulogan",
    "G1E": "777 (East) LoCoCaMaMa",
    "G1W": "777 (West) DaDiPaPi",
    "G1S": "777 (South) JAS-T'Boli",
    "G3": "3333 Conqueror's Coastal Gaming",
    "G4": "4G IV-Wheelers Riders",
    "G5": "5555 MAN OF STEEL",
    "AS26": "628 ALL STAR EXTREME",
    "G7": "7777 TOUR de FILIPINAS",
    "G81": "888 Route 1",
    "G82": "888 Route 2",
    "G83": "888 Route 3"
};


// 2. CHECKPOINT & ROUTE DIRECTORY (Para sa 8 ka Ruta)
// Pwede nimong usbon ang "AS26", "G5", "G1S" base sa saktong pangalan sa level/ruta sa imong riders.
const routeCheckpoints = {
    
    // --- Route 777N ---
    "G1N": {
        "CP 00": "Start Point - Ruta 2",
        "CP 01": "Unang Checkpoint sa Ruta 2",
        // ... i-type ang mga sunod ...
        "CP FL": "Finish Line - Ruta 2",
        "CP xx": "Stand By Me"
    },

    // --- Route 777E ---
    "G1E": {
        "CP 00": "Start Point - Ruta 2",
        "CP 01": "Unang Checkpoint sa Ruta 2",
        // ... i-type ang mga sunod ...
        "CP FL": "Finish Line - Ruta 2",
        "CP xx": "Stand By Me"
    },

    // --- Route 777W ---
    "G1W": {
        "CP 00": "Start Point - Ruta 2",
        "CP 01": "Unang Checkpoint sa Ruta 2",
        // ... i-type ang mga sunod ...
        "CP FL": "Finish Line - Ruta 2",
        "CP xx": "Stand By Me"
    },

    // --- Route 777S ---
    "G1S": {
        "CP xx": "Stand By Me"
    },

    // --- Route Mindanao Coastal Gaming ---
    "G3": {
        "CP 00": "Starting Grid Bunawan",
        "CP 02": "Davao Coastal Road",
        "CP 03": "McDo Petron Cogon Digos",
        "CP 04": "Flying V Otsenta",
        "CP 05": "Malita Municipal Plaza",
        "CP 06": "Joyce Paradise",
        "CP 07": "Baños Point Lighthouse",
        "CP 08": "JAS Municipal Hall",
        "CP 09": "TOUR Town Glan",
        "CP 10": "Plaza Heneral Santos",
        "CP 11": "Maitum Municipal Hall",
        "CP 12": "Baywalk Palimbang",
        "CP 13": "Lebak Roundball",
        "CP 14": "Grand Mosque of Cotabato",
        "CP 15": "Picung Tunnel",
        "CP 16": "Rotunda Park Pagadian",
        "CP 17": "Ipil Rotunda Obelisk",
        "CP 18": "Zamboanga City Signage",
        "CP 19": "Boyscout of the Philippines",
        "CP 20": "Limpana TRUSS Bridge",
        "CP 21": "Pangian Bridge",
        "CP 22": "Sibuco Municipality",
        "CP 23": "Siocon Rotonda Plaza",
        "CP 24": "Baliguian Eadle Landmark",
        "CP 25": "I Love Gutalac Landmard",
        "CP 26": "Liloy Municipal Hall",
        "CP 27": "Giant Chicken Statue",
        "CP 28": "Dipolog Rotonda",
        "CP 29": "Dapitan Park",
        "CP 29": "Rizal Shrine",
        "CP 30": "Tag-ulo",
        "CP 31": "Plaridel",
        "CP 32": "I Love Oroquieta",
        "CP 33": "Panguil Bay Bridge",
        "CP 34": "Iligan City (711/Petron)",
        "CP 35": "MV Beach & Pool Resort",
        "CP 36": "El Salvador City Hall",
        "CP 37": "Divine Mercy Statue",
        "CP 38": "Bugo CDO Shell Gasoline Station",
        "CP 39": "Sugbongcogon Municipal Hall",
        "CP 40": "The Bay Gingoog",
        "CP 41": "Magsaysay Munipal Park",
        "CP 42": "Cervantina Elementary School",
        "CP 43": "Vinapor Beach Park",
        "CP 44": "San Agustin Centennial Tree",
        "CP 45": "World War II Marker",
        "CP 46": "Nasipit Plaza",
        "CP 47": "PUNTA BRGY HALL",
        "CP 48": "LARIOSA BEACH RESORT",
        "CP 49": "SAN ANDREAS PLAZA",
        "CP 50": "BUENAVISTA PLAZA",
        "CP 51": "TINAGO ELEMENTARY SCHOOL",
        "CP 52": "FORTEZZA DE PAULA",
        "CP 53": "CABEZA DE BUENAVISTA",
        "CP 54": "DAPHNIE STORE",
        "CP 55": "MAGELLAN LANDING",
        "CP 56": "LUMBOCAN BRIDGE",
        "CP 57": "TOWER OF WAWAY ILHI",
        "CP 58": "PUROK LILOAN",
        "CP 59": "BADING BRGY HALL",
        "CP 60": "BLACK CAT",
        "CP 61": "BANZA CHURCH RUIN",
        "CP 62": "BANZA BRIDGE 2",
        "CP 63": "COCA COLA WH ",
        "CP 64": "Jollibee Cabadbaran",
        "CP 65": "Jabonga People's Park",
        "CP 66": "Hanagdong Project",
        "CP 67": "Looc Landmark",
        "CP 68": "Punta Bilar Lighthouse",
        "CP 69": "I Love Surigao",
        "CP 70": "Nabago Elementary School",
        "CP 71": "Claver 711",
        "CP 72": "Noventa View Deck",
        "CP 73": "Tandag City Baywalk Boulevard",
        "CP 74": "Hinatuan Signage",
        "CP 75": "Petron Cateel",
        "CP 76": "Baganga Sunrise Boulevard",
        "CP 77": "Pusan Point Caraga",
        "CP 78": "Balete Primary School",
        "CP 79": "WOW Manay Landmark",
        "CP 80": "Dahican Rotunda",
        "CP 81": "Mati Baywalk Park",
        "CP 82": "711/SeaOil Governor Generoso",
        "CP 83": "Centennial Tree (dedo na :-( )",
        "CP 84": "Cape San Agustin",
        "CP 85": "Manikling Rotonda",
        "CP 86": "Davao Oriental Welcome Park",
        "CP 87": "Diocesan Shrine of Our Mother of Pertual Help",
        "CP 88": "Fe Misa Ayala Seniors Park",
        "CP 89": "ELKAPITAN 's Burial Ground ",
        "CP 89": "Bugsay Landmark",
        "CP 89": "Panabo City Seawall & Park",        
        "CP FL": "Finish Line Bunawan Grid"
    },
    // --- Route 4 Wheels---
    "G4": {
        "CP 00": "Start Point - Ruta 4",
        "CP FL": "Finish Line - Ruta 4"
    },

    // --- Route 5555 MAN OF STEEL ---
    "G5": {
        "CP 000": "Starting Grid Bunawan",
        "CP 001": "Davao City Coastal Road",
        "CP 002": "McDo Cogon Digos",
        "CP 003": "Esso Gasoline Station, Paco, Kidapawan",
        "CP 004": "White Hills View, Sitio Dao Road, Arakan",
        "CP 005": "Philippine Eagle Monument",
        "CP 006": "Greek Hills",
        "CP 007": "OverView Nature & Culture Park",
        "CP 008": "3J Gazz, Quezon, Bukidnon",
        "CP 009": "Aglayan Roundball",
        "CP 010": "Lantaw 360 Camp & Cafe",
        "CP 011": "junction Tikalaan turn left",
        "CP 012": "711 Pangantukan",
        "CP 013": "Discovery Hotel Dangcagan",
        "CP 014": "Buagas Machine Shop, Carmen",
        "CP 015": "crash site atbang sa menteryo",
        "CP 016": "Bagontapay Roundball",
        "CP 017": "Tacul Elementary School",
        "CP 018": "Magsaysay Municipality",
        "CP 019": "Matanao, turn right to Savoy",
        "CP 020": "Columbio Municipal Hall",
        "CP 021": "Isulan Roundball",
        "CP 022": "711 Surallah",
        "CP 023": "Marbel Roundball",
        "CP 024": "BK's Kitchen @ Ondeng’s Food Park",
        "CP 025": "Bangkapayapaan Monument",
        "CP 026": "Flying V Otsenta Junction",
        "CP 027": "Malita Municipal Plaza",
        "CP 028": "Joyce Paradise",
        "CP 029": "Baños Point Lighthouse",
        "CP 030": "JAS Municipal Hall",
        "CP 031": "TOUR Town Glan",
        "CP 032": "Maasim Town Plaza",
        "CP 033": "Maitum Municipal Hall",
        "CP 034": "Baywalk Palimbang",
        "CP 035": "Kalamansig Municipal",
        "CP 036": "Lebak Municipal Portal / Lebak ",
        "CP 037": "The Grand Mosque of Cotabato",
        "CP 038": "People's Palace Cotabato City",
        "CP 039": "Alamada Municipal Hall",
        "CP 040": "Tent City",
        "CP 041": "WOWWAO",
        "CP 042": "KM0 Warawi",
        "CP 043": "Picong Tunnel",
        "CP 044": "Pagadian Rotonda Park",
        "CP 045": "Ipil Rotunda Obelisk",
        "CP 046": "Pasonanca Park",
        "CP 047": "Zamboanga City Signage",
        "CP 048": "Historic BSP Monument",
        "CP 049": "Limpana TRUSS Bridge",
        "CP 050": "Pangian Bridge",
        "CP 051": "Sibuco Municipal Hall",
        "CP 052": "Siocon Municipal Hall",
        "CP 053": "Liloy Municipal Hall",
        "CP 054": "Manukan Town Hall",
        "CP 055": "Dipolog City Hall",
        "CP 056": "New Dapitan City Hall",
        "CP 057": "I Love Oroquieta",
        "CP 058": "Hoyohoy View Deck",
        "CP 059": "Petron Tangub",
        "CP 060": "Panguil Bay Bridge",
        "CP 061": "Dapit Alim Shrine",
        "CP 062": "Maria Christina Falls",
        "CP 063": "Iligan City (711/Petron)",
        "CP 064": "El Salvador City Hall",
        "CP 065": "Devine Mercy Statue",
        "CP 066": "Shell CDO",
        "CP 067": "Atugan Nature Farm",
        "CP 068": "Valencia Jollibee",
        "CP 069": "San Fernando Cabanglasan Junction",
        "CP 070": "Manggaod",
        "CP 071": "Iba",
        "CP 072": "Kulaman",
        "CP 073": "Busdi",
        "CP 074": "Bulonay",
        "CP 075": "Magawa",
        "CP 076": "Magawa Bridge",
        "CP 077": "Lamingan",
        "CP 078": "Mintapud",
        "CP 079": "Gingoog Butuan Fork",
        "CP 080": "Bal-ason",
        "CP 081": "Kahulogan",
        "CP 082": "Claveria View Deck",
        "CP 083": "Municipal Hall of Claveria",
        "CP 084": "Balingasag Light House",
        "CP 085": "Balingoan",
        "CP 086": "The Bay Gingoog",
        "CP 087": "Magsaysay Munipal Park"
        "CP 088": "Vin4 (Jurassic) Blue Waters",
        "CP 089": "Bancasi",
        "CP 090": "Ezperanza Bridge",
        "CP 091": "Talacogon",
        "CP 092": "La Paz Signage",
        "CP 093": "Petron Loreto",
        "CP 094": "Loreto Municipal Hall",
        "CP 095": "Trento Rotonda",
        "CP 096": "Rotonda/711 San Francisco",
        "CP 097": "Bayugan Park",
        "CP 098": "Jollibee Cabadbaran",
        "CP 099": "Jabonga People's Park",
        "CP 100": "Hanagdong Project",
        "CP 101": "Looc Landmark",
        "CP 102": "Punta Bilar Lighthouse",
        "CP 103": "I Love Surigao",
        "CP 104": "Nabago Elementary School",
        "CP 105": "Claver 711",
        "CP 106": "Noventa View Deck",
        "CP 107": "Tandag Boulevard",
        "CP 108": "Lianga Signage",
        "CP 109": "Harip Beach",
        "CP 110": "Enchanted River",
        "CP 111": "Hinatuan Signage",
        "CP 112": "iLoveBislig",
        "CP 113": "Cuevas",
        "CP 114": "Monkayo",
        "CP 115": "Mt. Diwata",
        "CP 116": "Poblacion Boston",
        "CP 117": "Baganga Sunrise",
        "CP 118": "Pusan Point Caraga",
        "CP 119": "WOW Manay Landmark",
        "CP 120": "Dahican Rotunda",
        "CP 121": "DavOr Provincial Museum",
        "CP 122": "Mati Baywalk Park",
        "CP 123": "Mt. Hamiguitan World Heritage Park",
        "CP 124": "711/SeaOil Governor Generoso",
        "CP 125": "Centennial Tree General Generoso",
        "CP 126": "Cape San Agustin",
        "CP 127": "Manikling Rotonda",
        "CP 128": "Diocesan Shrine of Our Mother of Pertual Help",
        "CP 129": "711 Mawab",
        "CP 130": "Bilawa Mainit Falls",
        "CP 131": "Tambo View Deck",
        "CP 132": "Maragusan Landmark",
        "CP 133": "Saddle Road",
        "CP 134": "Nabunturan",
        "CP 135": "Montevista Rotonda",
        "CP 136": "Casoon National HighSchool",
        "CP 137": "LS Sarmiento Bridge",
        "CP 138": "Conception Elementary School",
        "CP 139": "Laak Municipal Hall",
        "CP 140": "w0w Assuncion",
        "CP 141": "Fe Misa Ayala Seniors Park",
        "CP 142": "ELKAPITAN's Burial Ground",
        "CP 143": "DavNor Signage",
        "CP 144": "Bugsay Landmark",
        "CP 145": "Panabo City Seawall & Park",
        "CP FL": "Finish Line Bunawan Grid", 
    },

    // --- RUTA 8: AS26 ---
    "AS26": {
        "CP 00": "Start Point / Assembly Area",
        "CP 01": "Mr. DIY Panabo",
        "CP 02": "Junction Paquibato - Kalagangan Rd / Calinan Rd.",
        "CP 03": "New Paquibato District Hall",
        "CP 04": "Pungco Hill",
        "CP 05": "Junction Panaga - Tapak Road / Paquibato - Kalagangan Rd",
        "CP 06": "Junction Kalagangan - Talaingod Rd",
        "CP 07": "Junction Bukidnon - Laak Road",
        "CP 08": "Sitio Bulo, Brgy Namnam, San Fernando, Bukidnon, Terracing Landscape View",
        "CP 09": "Pipisan Bridge, Sitio Pipisan, Brgy. Gupitan, Kapalong",
        "CP 10": "Lumondong Bridge / Falls, Sitio Lumondong, Brgy Gupitan, Kapalong",
        "CP 11": "Junction Kili-Kili, Sitio Kili-Kili, Brgy Gupitan, Kapalong",
        "CP 12": "Gatnaon Road, Sitio Butoy, Gupitan, Kapalong",
        "CP 13": "Junction Imelda, Brgy. Imelda, Laak",
        "CP 14": "Laak ta Bai",
        "CP 15": "Sampaguita Junction Park",
        "CP 16": "Sta Josefa Petron",
        "CP 17": "Crossing Brgy. Angas & Brgy. Awao",
        "CP 18": "Awao River Crossing (A)",
        "CP 19": "Awao River Crossing (B)",
        "CP 20": "Awao Ticket Booth",
        "CP 21": "Awao Falls",
        "CP 22": "Crossing Brgy. Angas & Brgy. Awao",
        "CP 23": "INC, Monkayo",
        "CP 24": "JESREL STORE, Mount Diwata",
        "CP 25": "GKK Santo Niño",
        "CP 26": "Goldie Mark Store, Purok 1-A, Mount Diwata",
        "CP 27": "Libunao Store",
        "CP 28": "Tru-Cut, Diwalwal",
        "CP 29": "Petron Boston",
        "CP 30": "Aliwagwag Falls Ecopark",
        "CP 31": "Manurigao highlands 5650 ft. Above sea level",
        "CP 32": "Shadol's Coffee Paste",
        "CP 33": "Maragusan Rotunda",
        "CP 34": "Araibo, Pantukan, Davao de Oro Checkpoint",
        "CP 35": "Special Village, Las Arenas, Pantukan",
        "CP 36": "Motor Parts, Brgy. Tagugpo, Pantukan",
        "CP 37": "Napapan Mandatory Photo Op",
        "CP 38": "Jolibee Pantukan",
        "CP FL": "ELKAPITAN's Headstone (Finish Line)",
        "CP xx": "Stand By Me"
    },

    // --- Route 7777 ---
    "G7": {
        "CP 00": "Start Point",
        "CP FL": "Finish Line",
        "CP xx": "Stand By Me"
    },

    // --- Route 81 ---
    "G81": {
        "CP 00": "Start Grid Bunawan",
        "CP 01": "Paquibato",
        "CP 02": "Kalagangan",
        "CP 03": "Malaybalay Old City Hall",
        "CP 04": "Gaisano Puerto",
        "CP 05": "Gusa coastal road",
        "CP 06": "Vhilma Store",
        "CP 07": "Vjandep Pastel Of Camiguin",
        "CP 08": "Country Village Hotel",
        "CP 09": "Jollibee CDO Vamenta",
        "CP 10": "Cogon Public Market",
        "CP 11": "Orange Graphic Materials Inc",
        "CP 12": "CamHills - Home of Gecko Café",
        "CP 13": "Ministry Incorporated, kamakawan",
        "CP 14": "Macapaya Livelihood Center",
        "CP 15": "Camaman-an Barangay Hall",
        "CP 16": "Camaman-an Elementary School",
        "CP 17": "Yuri’s Arts and Crafts",
        "CP 18": "Amaya View",
        "CP 19": "Indahag Barangay Hall",
        "CP 20": "Cagayan de Oro International Convention Center",
        "CP 21": "High Ridge",
        "CP 22": "Chesamz Halal Pater Station",
        "CP 23": "CDO PET DOCTOR",
        "CP 24": "Vermont Cafe & Resort",
        "CP 25": "The Copeland",
        "CP 26": "Gasa (By: VjANDEP) CDO Uptown Branch",
        "CP 27": "Midway Seafooods Grill and Restaurant",
        "CP 28": "Jollibee Bulua",
        "CP 29": "Jollibee Igpit Opol",
        "CP 30": "RMC PETROL OPOL BRANCH",
        "CP 31": "Norminring Enduro Park",
        "CP 32": "Bagocboc National High School",
        "CP 33": "San Simon Health Center",
        "CP 34": "Baikingon Elementary School",
        "CP 35": "Hinaplanon - Baikingon Basketball Court",
        "CP 36": "Juanne MBG",
        "CP 37": "GRAM Convenience Store Pagatpat",
        "CP 38": "VELOX ENERGY",
        "CP 39": "San Simon - Pagatpat Bridge",
        "CP 40": "Sunrise Café",
        "CP 41": "Alluka Camp",
        "CP 42": "Baluarte Elementary School",
        "CP 43": "TAGPANGI NATIONAL HIGH SCHOOL",
        "CP 44": "Dansoliwood Viewdeck Cafe",
        "CP 45": "Bolao Cold Spring Signage",
        "CP 46": "Sinulom Falls, de Oro, Tignapoloan"
        "CP 47": "Rogongon Agricultural High School -Main",
        "CP 48": "Digkilaan Barangay Hall",
        "CP 49": "Paseo De Santiago",
        "CP 50": "Cheding's Peanuts",
        "CP 51": "Overton-Abaga-Suarez Cross Road",
        "CP 52": "Kilometer Zero (KM 0.000) Point Marker Marawi",
        "CP 53": "Balindong District Hospital",
        "CP 54": "J & S HARDWARE",
        "CP 55": "Lumbatan Municipal Hall",
        "CP 56": "BigBrew Tamparan",
        "CP 57": "Marawi City Rizal Park",
        "CP 58": "King's Bakeshop And Snack Inn, Baloi",
        "CP 59": "Abuno-Tagoloan Boundary",
        "CP 60": "The Pantry Iligan",
        "CP 61": "FAT PAULY'S TAPROOM+PUB",
        "CP 02": "D’Holy 3 Nature Park & Family Resort",
        "CP 63": "Lantud Bridge",
        "CP 04": "Mamaon Border Control Point",
        "CP 65": "JABLA store",
        "CP 66": "Jollibee Quezon",
        "CP 67": "PLDT Calinane",
        "CP FL": "Finish Line Bunawan Grid"
    },

    // --- Route 82 ---
    "G82": {
        "CP 00": "Start Point",
        "CP 01": "Unang Checkpoint",
        // ... i-type ang mga sunod ...
        "CP FL": "Finish Line",
        "CP xx": "Stand By Me"
    },

    // --- Route 83 ---
    "G83": {
        "CP 00": "Start Point",
        "CP 01": "Unang Checkpoint",
        // ... i-type ang mga sunod ...
        "CP FL": "Finish Line",
        "CP xx": "Stand By Me"
    },

};